### PR TITLE
Add v11.4 to supported versions

### LINKED ISSUE #59: Support MariaDB 11.4
11.4 is available for docker.

If a database is imported using drush sql-sync, it breaks when the server uses a later version of mariadb.
https://mariadb.org/mariadb-dump-file-compatibility-change/

I think the easiest fix is to be able to set your local version to the save as the server, but our options are currently limited to releases that don't contain the fix.

More links:
https://mariadb.org/mariadb-dump-file-compatibility-change/
https://jira.mariadb.org/browse/MDEV-34203
https://ddev.com/blog/mariadb-dump-breaking-change/

### PR DESCRIPTION
**Pull request by mortona42**
Added 11.4

Closes #59

### Bare minimum self-checks

> [What do you think of a person who only does the bare minimum?](https://getyarn.io/yarn-clip/dcf80710-425e-478b-bde1-c107bd11e849)

- [X] I've updated this PR with the latest code from `main`
- [?] I've done a cursory QA pass of my code locally
- [?] I've ensured all automated status check and tests pass
- [X] I've [connected this PR to an issue](https://help.zenhub.com/support/solutions/articles/43000010350-connecting-pull-requests-to-github-issues)

### Pieces of flare

- [ ] I've written a unit or functional test for my code
- [ ] I've updated relevant documentation it my code changes it
- [ ] I've updated this repo's README if my code changes it
- [ ] I've updated this repo's CHANGELOG with my change unless its a trivial change (like updating a typo in the docs)

### Finally

- [ ] I've [requested a review](https://help.github.com/en/articles/requesting-a-pull-request-review) with relevant people

If you have any issues or need help please join the `#contributors` channel in the [Lando slack](https://www.launchpass.com/devwithlando) and someone will gladly help you out!

You can also check out the [coder guide](https://docs.lando.dev/contrib/coder.html).

### CODE REVIEW

**Comment by reynoldsalec** [comment]
Tests are erroring out asking for the `node` service when setting up Lando; should be unrelated to this PR. Possible it's an issue with the latest `lando-dev-slim`? Might deserve testing out some PRs on other plugins and see if they have the same problem.

For this PR, we should add a 11.4 test to the suite and update the docs to reflect the new version being available.

**Comment by AaronFeledy** [comment]
Yeah, others are seeing Lando fail in GHA as well: lando/setup-lando#50

**Comment by reynoldsalec** [comment]
Thanks for the reference @AaronFeledy. Looks like a couple things are going on; first error appears to occur on running `lando version` on https://github.com/lando/setup-lando/blob/2aebacd1f41b906c82b2c2d5f3e326fc0a4b8bfe/setup-lando.js#L130.

For some reason it thinks the `node` Lando plugin should be installed...looks like Lando is bootstrapping with the `.lando.yml` that's at the root of the `mariadb` project when running `lando version` and that's causing that immediate error.

I made a semi-bogus `.lando.yml` to replace that with and now I'm getting past that error to see one that seems to indicate it's unable to find `docker-compose`, which sounds like it may be related to https://github.com/lando/setup-lando/issues/50

**Review by AaronFeledy — APPROVED** [review]

**Comment by reynoldsalec** [comment]
Remerged that as #66 to get all the tests running with the new Lando, should be good, thanks @mortona42!

**Pull request closed without merging**
